/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'deep-black': '#000000',
        'pure-white': '#FFFFFF',
        'signal-red': '#FF3B3B',
        'zinc-muted': '#A1A1AA',
        primary: '#000000',
        'primary-container': '#1b1b1b',
        'on-primary': '#ffffff',
        secondary: '#bb0017',
        'secondary-container': '#e2242a',
        'on-secondary': '#ffffff',
        surface: '#faf8ff',
        'surface-dim': '#dad9e3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3fc',
        'surface-container': '#eeedf7',
        'surface-container-high': '#e8e7f1',
        'surface-container-highest': '#e2e1eb',
        'surface-variant': '#e2e1eb',
        'on-surface': '#1a1b22',
        'on-surface-variant': '#4c4546',
        'on-background': '#1a1b22',
        background: '#faf8ff',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
        'inverse-surface': '#2f3037',
        'inverse-on-surface': '#f1f0f9',
        'surface-tint': '#5e5e5e',
        'inverse-primary': '#c6c6c6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        grotesk: ['"Space Grotesk"', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      maxWidth: {
        container: '1280px',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
        'fade-up': 'fade-up 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.5s ease-out forwards',
      },
    },
  },
  plugins: [],
};
